trigger_type = "interpreted"

[server]
server_type = "webhook"
listen_addr = "127.0.0.1:8080"
use_tls = false

[[server.endpoints]]
path = "/merged"
trigger_name = "github-merged"

[[triggers]]
name = "github-merged"
plugin_path = "./example-plugins/python/github-merged.py"
