[[triggers]]
name = "github"
type = "webook"
url_path = "/test/endpoint"

[[checkers]]
name = "jira"
retry_strategy = "linear"
strict_evaluation = true

[[handlers]]
name = "slack"
retry_strategy = "linear"
