trigger_type = "webhook"
listen_addr = "127.0.0.1:8080"

[[triggers]]
name = "github"
url_path = "/test"

[[checkers]]
name = "jira"
retry_strategy = "linear"
strict_evaluation = true

[[handlers]]
name = "slack"
retry_strategy = "linear"
