trigger_type = "unix_socket"
listen_addr = "/home/jbaublitz/miss-demeanor"

[[triggers]]
name = "github"
url_path = "/test"

[[checkers]]
name = "jira"
retry_strategy = "linear"
strict_evaluation = true

[[handlers]]
name = "slack"
retry_strategy = "linear"
