[server]
server_type = "webhook"
listen_addr = "127.0.0.1:8080"
use_tls = true

[[server.endpoints]]
path = "/pr"
trigger_name = "github-pr"

[[server.endpoints]]
path = "/merged"
trigger_name = "github-merged"

[[triggers]]
name = "github-merged"
plugin_path = "./example-plugins/golang/github-merged.so"
