[package]
name = "miss-demeanor"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]

[dependencies]
env_logger = "*"
futures = "*"
getopts = "*"
hyper = "*"
hyper-tls = { git = "https://github.com/hyperium/hyper-tls", branch = "master" }
libc = "*"
libloading = "*"
log = "*"
native-tls = "*"
serde = "*"
serde_derive = "*"
tokio = "*"
tokio-io = "*"
tokio-threadpool = "*"
toml = "*"

[dependencies.miss-demeanor-pluginutils]
path = "./miss-demeanor-pluginutils"
version = "0.1.0"
features = ["rust"]
