[package]
name = "miss-demeanor"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]

[dependencies]
env_logger = "*"
futures = "*"
getopts = "*"
http = "*"
hyper = "*"
hyper-tls = "0.3.0"
libc = "*"
libloading = "*"
log = "*"
native-tls = "*"
serde = "*"
serde_derive = "*"
tokio = "*"
toml = "*"

[dependencies.miss-demeanor-pluginutils]
path = "./miss-demeanor-pluginutils"
version = "0.1.0"
features = ["rust"]
