[package]
name = "github-merged"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
edition = "2018"

[lib]
name = "githubmerged"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
